name: Basic Workflow

on: workflow_dispatch

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a Bash Script
        run: |
          echo "Hello, World! This is a basic workflow running on Nektos/Act."
