name: Environment and Secrets Usage

on: workflow_dispatch

jobs:
  use-env-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Environment Variable
        run: |
          echo "Environment Variable DB_HOST is $DB_HOST"
          echo "Environment Variable LOG_LEVEL is $LOG_LEVEL"
        env:
          DB_HOST: ${{ env.DB_HOST }}
          LOG_LEVEL: ${{ env.LOG_LEVEL }}

      - name: Use Secret for API Key
        run: |
          echo "Secret API_KEY is $API_KEY"
          echo "Secret DB_PASSWORD is $DB_PASSWORD"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Fetch User Repositories Using GITHUB_TOKEN
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
